version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    image: backend_localtomongo
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
